### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by jakevdp** [comment]
I think I'm going to move to depending on Altair, in which case we won't have to directly reference vega/vega3 here.

**Comment by domoritz** [comment]
Excellent. Feel free to close this PR then.

**Comment by domoritz** [comment]
Should we close this since pdvega now uses altair?

**Comment by jakevdp** [comment]
Yes, we need to update to depend on Altair instead.

**Pull request closed without merging**
