### PR TITLE
support figsize

### PR DESCRIPTION
**Pull request by Casyfill**
Adding figsize support to core plotting functions - same approach as for pdvega.plotting functions.

also, moved `warn_if_keywords_unused` to the end of each function

### CODE REVIEW

**Comment by Casyfill** [comment]
hm, not sure I understand why it failing here

**Comment by Casyfill** [comment]
note - I did't change doc strings as I don't want to encourage people to use `figsize` over width/height

**Comment by jakevdp** [comment]
Looks good – ready for merge?

**Comment by Casyfill** [comment]
I think so!

**Comment by jakevdp** [comment]
great, thanks!

**Pull request merged**
